2020-12-04 18:56:22,322 ERROR 36647 nodejs.ClusterClientNoResponseError: client no response in 342079ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 36647
hostname: caoyouzhi.local

2020-12-04 19:05:06,188 ERROR 36647 nodejs.ClusterClientNoResponseError: client no response in 483833ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 36647
hostname: caoyouzhi.local

2020-12-04 20:04:49,726 ERROR 36647 nodejs.ClusterClientNoResponseError: client no response in 2463374ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 36647
hostname: caoyouzhi.local

2020-12-04 20:20:54,626 ERROR 36647 nodejs.ClusterClientNoResponseError: client no response in 944841ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 36647
hostname: caoyouzhi.local

2020-12-04 23:07:06,318 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 708893ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 08:30:08,146 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 33761330ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 08:46:16,422 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 968027ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 09:26:16,946 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 540291ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 09:30:13,784 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 156813ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 09:47:55,457 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 100507ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

