2020-12-05 10:01:54,700 INFO 37814 [egg-logrotator] agent logger reload: got log-reload message
2020-12-05 10:47:45,356 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 148724ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 11:20:30,886 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1945501ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 11:33:36,311 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 745408ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 13:23:18,717 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1981640ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 14:29:21,565 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 3902834ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 14:54:49,582 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1487996ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 16:42:45,674 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 6456070ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 18:30:59,717 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 6454026ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 18:41:34,658 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 614916ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 18:43:33,269 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 78508ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 19:01:48,301 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1054939ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 19:56:20,317 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 3252004ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 20:09:38,076 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 577091ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-05 21:11:43,973 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 3725888ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 00:15:26,514 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 578489ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 01:40:42,522 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 5095975ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 01:50:42,429 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 579859ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 05:29:39,366 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 13116911ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 05:39:37,292 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 577907ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 08:37:32,715 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 10655391ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 08:58:12,602 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1219872ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 10:08:23,617 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 4191000ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 10:29:03,157 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1219521ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 11:07:46,662 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 2283488ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 11:19:21,213 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 654526ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 15:32:46,039 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 577851ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 16:52:34,859 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 4768808ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 17:05:33,867 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 578358ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 19:29:07,792 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 8593905ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 19:40:07,590 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 579763ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 19:55:02,004 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 894406ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 20:20:03,244 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1221180ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 21:01:44,238 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 2500987ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-06 21:32:25,521 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1221166ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-07 09:13:17,628 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 42031519ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-07 09:46:35,667 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1997745ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-07 11:28:12,802 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 511263ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-07 11:29:25,376 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 72540ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-07 11:32:30,321 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 144898ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-07 12:37:04,005 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1813417ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-07 13:45:52,048 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 4104053ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-07 14:38:33,380 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 1301110ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

2020-12-07 14:41:41,799 ERROR 37814 nodejs.ClusterClientNoResponseError: client no response in 148528ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 37814
hostname: caoyouzhi.local

